sudo: false
language: ruby
cache:
  bundler: true
  yarn: true
rvm:
  - 2.3.6
  - 2.4.3
  - 2.5.0
env:
  - RAILS_ENV=test WIKIDATA_SITE=test.wikidata.org
before_install:
  - gem update --system
  - cp config/database.yml.sample config/database.yml
  - . $HOME/.nvm/nvm.sh
  - nvm install 8.11
  - nvm use 8.11
install:
  - bundle install --jobs=3 --retry=3
  - yarn install
before_script:
  - bundle exec rake db:create db:schema:load db:test:prepare
script:
  - bundle exec rake
