#!/usr/bin/env bash

# Make sure we're in the correct directory
cd "$(dirname "$0")/.."

# Setup the environment
source ./script/toolforge-setup

# Add all the scripts that you want to be run daily here
bin/rails verification_page:load:all
bin/rails verification_page:generate:all
bin/rails data_check:update
