#!/usr/bin/env bash

set -e

# Make sure we're in the correct directory
cd "$(dirname "$0")/.."

# Add custom Ruby version to PATH
export PATH="$HOME/ruby-2.4.1/bin:$PATH"
export PATH="$HOME/node-v8.11.2-linux-x64/bin:$PATH"
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

# Install latest dependencies
bundle install --deployment --without development test --path vendor

# Load required environment variables
if [[ -f environment_variables.sh ]]; then
  . environment_variables.sh
fi

# Start the rack server
export RAILS_ENV=production
exec ./script/server
