#!/usr/bin/bash

# Add custom versions of tools to the PATH
export PATH="$HOME/ruby-2.4.1/bin:$PATH"
export PATH="$HOME/node-v8.11.2-linux-x64/bin:$PATH"
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

# Load required environment variables
if [[ -f environment_variables.sh ]]; then
  source environment_variables.sh
fi

# Install latest dependencies
bundle install --deployment --without development test --path vendor
